version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.43
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  gateway:
    image: apache/apisix:3.2.0-debian
    volumes:
      - ./gateway/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./gateway/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080"
  
  catalog:
    build: ./catalog/catalog
    image: somkiat/catalog:1.0
    environment:
      APP_PRICING_ENDPOINT: http://pricing:3000/prices
      APP_STOCK_ENDPOINT: http://stock:3000/stocks
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=catalog
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
  
  # pricing:
  #   build: ./pricing
  #   environment:
  #     OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
  #     OTEL_RESOURCE_ATTRIBUTES: service.name=pricing
  #     OTEL_METRICS_EXPORTER: none
  #     OTEL_LOGS_EXPORTER: none

  stock:
    build: ./stock
    image: somkiat/stock:1.0
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=stock
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
  
  database:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: database
    ports:
      - "1433:1433"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=stock
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: zitgmLwmp1@q
      MSSQL_PID: Developer
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PzitgmLwmp1@q", "-Q", "select 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s