version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.43
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  gateway:
    image: apache/apisix:3.2.0-debian
    volumes:
      - ./gateway/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./gateway/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080"
  
  catalog:
    build: ./catalog/catalog
    environment:
      APP_PRICING_ENDPOINT: http://pricing:3000/prices
      APP_STOCK_ENDPOINT: http://stock:3000/stocks
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=catalog
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
  
  # pricing:
  #   build: ./pricing
  #   environment:
  #     OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
  #     OTEL_RESOURCE_ATTRIBUTES: service.name=pricing
  #     OTEL_METRICS_EXPORTER: none
  #     OTEL_LOGS_EXPORTER: none

  stock:
    build: ./stock
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=stock
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
  
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=stock
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: zitgmLwmp1@q