version: "3"

services:
  jaeger:
    build: 
      context: ./jaeger
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - demo
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - demo

  grafana:
    image: grafana/grafana-oss:8.5.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/etc/grafana/provisioning
    networks:
      - demo

  gateway:
    image: apache/apisix:3.2.0-debian
    volumes:
      - ./gateway/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./gateway/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080"
      - "9091:9091"
    environment:
      - TZ=Asia/Bangkok
    # depends_on:
    #   - catalog
    networks:
      - demo
  
  catalog:
    build: ./catalog/catalog
    image: somkiat/catalog:1.0
    environment:
      APP_PRICING_ENDPOINT: http://pricing:3000/prices
      APP_STOCK_ENDPOINT: http://stock:3000/stocks
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=catalog
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
    ports:
      - "9999:80"

    depends_on:
      jaeger:
        condition: service_started
      pricing:
        condition: service_healthy
      stock:
        condition: service_healthy
    #   database:
    #     condition: service_healthy
    networks:
      - demo
  
  pricing:
    build: ./pricing
    image: somkiat/pricing:1.0
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=pricing
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      DATABASE: demo-db
      DATABASE_HOST: mysql
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - demo

  stock:
    build: ./stock
    image: somkiat/stock:1.0
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=stock
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      DATABASE: demo-db
      DATABASE_HOST: mysql
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - demo
  
  sqlcmd:
    build:
      context: ./database
      dockerfile: Dockerfile
    stdin_open: true
    networks:
      - demo

  database:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: database
    volumes:
      - ./database/setup.sql:/app/setup.sql
    ports:
      - "1433:1433"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=stock
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: zitgmLwmp1@q
      MSSQL_PID: Developer
    # healthcheck:
    #   test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PzitgmLwmp1@q", "-Q", "select 1"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s
    networks:
      - demo

  mysql:
    build:
      context: ./mysql
    container_name: mysql
    image: somkiat/mysql:1.0
    environment:
      - MYSQL_DATABASE=demo-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=xxx
    healthcheck:
      test: ["CMD", "mysql", "-hlocalhost", "-uuser", "-ppass", "-e", "USE demo-db;"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - demo

networks:
  demo:
    driver: bridge