scrape_configs:
  - job_name: 'api-gateway'
    scrape_interval: 5s
    metrics_path: '/apisix/prometheus/metrics'
    static_configs:
      - targets: ['gateway:9091']
        labels:
          application: 'api-gateway'